### ISSUE TITLE
app stop when install debug or release apk

### ISSUE THREAD

**Issue by jayeshpansheriya** [AgoraIO/Flutter-RTM#38]
app is working fine directly run from computer in simulator and real device,
but when i generate debug or release apk and install it in real device app is stop.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by plutoless** [comment]
usually this is caused by abi-filter, please double check that.

**Comment by LichKing-2234** [comment]
pls provide the crash log

**Comment by jayeshpansheriya** [comment]
> usually this is caused by abi-filter, please double check that.


 ndk {
            abiFilters 'armeabi-v7a', 'x86' ,'arm64-v8a'
        }

**Comment by jayeshpansheriya** [comment]
> pls provide the crash log

 --------- beginning of crash
2020-05-08 10:21:05.188 25559-25559/com.example.agoraflutterquickstart E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.agoraflutterquickstart, PID: 25559
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/expand/b6a7c026-a55f-41b3-81fd-ef0a1bbdd477/app/com.example.agoraflutterquickstart-ln_h3PBMqx2uzZnVfVq2hQ==/base.apk"],nativeLibraryDirectories=[/mnt/expand/b6a7c026-a55f-41b3-81fd-ef0a1bbdd477/app/com.example.agoraflutterquickstart-ln_h3PBMqx2uzZnVfVq2hQ==/lib/arm64, /mnt/expand/b6a7c026-a55f-41b3-81fd-ef0a1bbdd477/app/com.example.agoraflutterquickstart-ln_h3PBMqx2uzZnVfVq2hQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:120)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:88)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:48)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:24)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
        at android.app.ActivityThread.access$1200(ActivityThread.java:206)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by jayeshpansheriya** [comment]
you can also check code from my github  repository.

[https://github.com/jayeshpansheriya/Agora-Flutter-Quickstart](https://github.com/jayeshpansheriya/Agora-Flutter-Quickstart)

**Comment by LichKing-2234** [comment]
what command did you use to generate debug or release .apk file?

**Comment by jayeshpansheriya** [comment]
flutter build => for debug
flutter build apk --release. =>  for release apk

**Comment by LichKing-2234** [comment]
try gradle assemble?

**Comment by jayeshpansheriya** [comment]
> try gradle assemble?

yes

**Comment by LichKing-2234** [comment]
is it worked?

**Comment by jayeshpansheriya** [comment]
> is it worked?

no


i have shared my github repository you can check it

**Comment by jayeshpansheriya** [comment]
in ios build  i got 
login failed errorCode:9

No permission. This is for internal SDK internal use only, and it will not return to the application through any API or callback event.

**Comment by LichKing-2234** [comment]
No permission exists. Check if the user has granted access to the audio or video device.

**Comment by jayeshpansheriya** [comment]
<key>NSCameraUsageDescription</key>
	<string>The app tries to use your camera</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>The app tries to use your microphone</string>


i have already added and permission is granted

**Comment by jayeshpansheriya** [comment]
> > usually this is caused by abi-filter, please double check that.
> 
> ndk {
> abiFilters 'armeabi-v7a', 'x86' ,'arm64-v8a'
> }
> 
> i have already added.

i have already agged all configuration then why my build apk is not working?

**Comment by LichKing-2234** [comment]
@jayeshpansheriya Any soluation?

**Comment by jayeshpansheriya** [comment]
> @jayeshpansheriya Any soluation?
R8 is the new code shrinker from Google, and it’s enabled by default when you build a release APK or AAB. To disable R8, pass the --no-shrink flag to flutter build apk or flutter build appbundle.

flutter build apk --release --no-shrink
